export { default as FanScreen } from './Fan';
export { default as DMXScreen } from './DMX';
export { default as Ac } from './DemoKit/AC';
export { default as HomeScreen } from './Home';
export { default as StarScreen } from './Star';
export { default as Dmx } from './DemoKit/DMX';
export { default as HVACScreen } from './HVAC';
export { default as RGBWScreen } from './RGBW';
export { default as Fan } from './DemoKit/Fan';
export { default as LightScreen } from './Light';
export { default as RGBW } from './DemoKit/RGBW';
export { default as MusicScreen } from './Music';
export { default as Moods } from './DemoKit/Mood';
export { default as Demokitzone } from './DemoKit';
export { default as Light } from './DemoKit/Light';
export { default as Music } from './DemoKit/Music';
export { default as Media } from './DemoKit/Media';
export { default as Camera } from './DemoKit/Camera';
export { default as CurtainScreen } from './Curtain';
export { default as SettingScreen } from './Setting';
export { default as SecurityScreen } from './Security';
export { default as Curtain } from './DemoKit/Curtain';
export { default as LoginScreen } from './LoginScreen';
export { default as AlaramVCScreen } from './AlaramVC';
export { default as ByBrowserScreen } from './ByBrowser';
export { default as SplashScreen } from './SplashScreen';
export { default as ForgetScreen } from './ForgetScreen';
export { default as SchedulingScreen } from './Scheduling';
export { default as IrrigationScreen } from './Irrigation';
export { default as ByFtpServerScreen } from './ByFtpServer';
export { default as Irrigation } from './DemoKit/Irrigation';
export { default as ACSetting } from './DemoKit/AC/AC Setting';
export { default as FanSetting } from './DemoKit/Fan/Fan Setting';
export { default as DMXSetting } from './DemoKit/DMX/DMX Setting';
export { default as OtherControl } from './DemoKit/Other Controls';
export { default as CentralControlScreen } from './CentralControl';
export { default as LanguageSettingScreen } from './LanguageSetting';
export { default as DatabaseSettingScreen } from './DatabaseSetting';
export { default as RGBWSetting } from './DemoKit/RGBW/RGBW Setting';
export { default as MoodSetting } from './DemoKit/Mood/Mood Setting';
export { default as GlobalNetworkScreen } from './GlobalNetworkSetting';
export { default as LightSetting } from './DemoKit/Light/Light Setting';
export { default as MusicSetting } from './DemoKit/Music/Music Setting';
export { default as CurtainSetting } from './DemoKit/Curtain/Curtain Setting';
export { default as SchedulingDropScreen } from './Scheduling/Schedulinginner';
export { default as OtherSetting } from './DemoKit/Other Controls/Other Setting';
